/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package comm.zjgsu.face;

public class npddetect {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected npddetect(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(npddetect obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        detectJNI.delete_npddetect(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public npddetect() {
    this(detectJNI.new_npddetect__SWIG_0(), true);
  }

  public npddetect(int minFace, int maxFace) {
    this(detectJNI.new_npddetect__SWIG_1(minFace, maxFace), true);
  }

  public void load(String modelpath) {
    detectJNI.npddetect_load(swigCPtr, this, modelpath);
  }

  public int gridScan(SWIGTYPE_p_unsigned_char I, int width, int height, double stepR, double thresR) {
    return detectJNI.npddetect_gridScan__SWIG_0(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(I), width, height, stepR, thresR);
  }

  public int gridScan(SWIGTYPE_p_unsigned_char I, int width, int height, double stepR) {
    return detectJNI.npddetect_gridScan__SWIG_1(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(I), width, height, stepR);
  }

  public int gridScan(SWIGTYPE_p_unsigned_char I, int width, int height) {
    return detectJNI.npddetect_gridScan__SWIG_2(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(I), width, height);
  }

  public int detect(byte[] I, int width, int height) {
    return detectJNI.npddetect_detect__SWIG_0(swigCPtr, this, I, width, height);
  }

  public int detect(SWIGTYPE_p_cv__Mat ima) {
    return detectJNI.npddetect_detect__SWIG_1(swigCPtr, this, SWIGTYPE_p_cv__Mat.getCPtr(ima));
  }

  public int detect(String imgPath) {
    return detectJNI.npddetect_detect__SWIG_2(swigCPtr, this, imgPath);
  }

  public int prescandetect(byte[] I, int width, int height, double stepR, double thresR) {
    return detectJNI.npddetect_prescandetect__SWIG_0(swigCPtr, this, I, width, height, stepR, thresR);
  }

  public int prescandetect(byte[] I, int width, int height, double stepR) {
    return detectJNI.npddetect_prescandetect__SWIG_1(swigCPtr, this, I, width, height, stepR);
  }

  public int prescandetect(byte[] I, int width, int height) {
    return detectJNI.npddetect_prescandetect__SWIG_2(swigCPtr, this, I, width, height);
  }

  public vectori getXs() {
    return new vectori(detectJNI.npddetect_getXs(swigCPtr, this), false);
  }

  public vectori getYs() {
    return new vectori(detectJNI.npddetect_getYs(swigCPtr, this), false);
  }

  public vectori getSs() {
    return new vectori(detectJNI.npddetect_getSs(swigCPtr, this), false);
  }

  public SWIGTYPE_p_std__vectorT_float_t getScores() {
    return new SWIGTYPE_p_std__vectorT_float_t(detectJNI.npddetect_getScores(swigCPtr, this), false);
  }

  public void draw(String arg0) {
    detectJNI.npddetect_draw(swigCPtr, this, arg0);
  }

}
